# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bps <- function(maxTime, rate_f, factors, local_updates, Data, y, x0, theta0, trac_coords, tmax = 1.0, poly_order = 0L, nmax = 10^6L, burn = -1L, ref_rate = 0.1, sphere = FALSE) {
    .Call(`_ccpdmp_bps`, maxTime, rate_f, factors, local_updates, Data, y, x0, theta0, trac_coords, tmax, poly_order, nmax, burn, ref_rate, sphere)
}

linear_inv_t <- function(a, b, u, tmax) {
    .Call(`_ccpdmp_linear_inv_t`, a, b, u, tmax)
}

exp_inv_t <- function(a, b, u) {
    .Call(`_ccpdmp_exp_inv_t`, a, b, u)
}

sim_rate_poly <- function(eval_times, eval_rates, poly_order) {
    .Call(`_ccpdmp_sim_rate_poly`, eval_times, eval_rates, poly_order)
}

zigzag_cpp <- function(maxTime, rate_f, factors, local_updates, Data, y, x0, theta0, trac_coords, tmax = 1.0, poly_order = 0L, nmax = 10^6L, burn = -1L) {
    .Call(`_ccpdmp_zigzag_cpp`, maxTime, rate_f, factors, local_updates, Data, y, x0, theta0, trac_coords, tmax, poly_order, nmax, burn)
}

