# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

linear_inv_t <- function(a, b, u, tmax) {
    .Call(`_ccpdmp_linear_inv_t`, a, b, u, tmax)
}

exp_inv_t <- function(a, b, u) {
    .Call(`_ccpdmp_exp_inv_t`, a, b, u)
}

sim_rate_poly <- function(eval_times, eval_rates, poly_order) {
    .Call(`_ccpdmp_sim_rate_poly`, eval_times, eval_rates, poly_order)
}

